AppFinalCaminhao/Models/ErrorViewModel.cs
using System;

namespace AppFinalCaminhao.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AppFinalCaminhao/Controllers/HomeController.cs
using AppFinalCaminhao.Models;
using AppFinalCaminhao.Infra.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace AppFinalCaminhao.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        
        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        
        public IActionResult Index()
        {
            
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AppFinalCaminhao/Controllers/NewViewsController.cs
using AppFinalCaminhao.Infra.Repository;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using AppFinalCaminhao.Infra.Models;
using AppFinalCaminhao.Service.Inteface;
using AppFinalCaminhao.Service.CaminhaoService;

namespace AppFinalCaminhao.Controllers
{
    public class NewViewsController : Controller
    {
        private readonly ICaminhaoService _caminhaoService;
        public NewViewsController(ICaminhaoService caminhaoService)
        {
            _caminhaoService = caminhaoService;
        }

        public IActionResult Index()
        {
            List<Caminhao> ListaCaminhoes = _caminhaoService.ListarOsCaminhoes()  ;
            return View(ListaCaminhoes);
            }

        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Delete(int id)
        {
            Caminhao caminhao = _caminhaoService.BuscarPorId(id);

            return View(caminhao);
        }

        public IActionResult Details(int id)
        {
            Caminhao caminhao = _caminhaoService.BuscarPorId(id);
            return View(caminhao);
        }

        //Perguntar por que a entrada da Edit é um caminhao não um Id;
        public IActionResult Edit(int id)
        {
            var caminhao = _caminhaoService.BuscarPorId(id);
            return View(caminhao);
        }

        [HttpPost]
        public IActionResult Create(Caminhao caminhao)
        {
            
            try
            {
                if (ModelState.IsValid)
                {
                    _caminhaoService.AnunciarCaminhao(caminhao);
                    TempData["MensagemSucesso"] = "Carro cadastrado com sucesso";
                    return RedirectToAction("Index", _caminhaoService.ListarOsCaminhoes());
                }
                return View(caminhao);
            }
            catch (System.Exception erro)
            {
                TempData["MensagemErro"] = $"Ops,deu problema para o cadastro,detalhe do erro:{erro.Message}";
                return RedirectToAction("Index", _caminhaoService.ListarOsCaminhoes());
            }
        }

        //Perguntar por que a entrada da Edit é um caminhao não um Id;
        [HttpPost]
        public IActionResult Edit(Caminhao caminhao )
        {
            
            
            try
            {
               if (ModelState.IsValid)
                {

                    _caminhaoService.Editando(caminhao);
                    TempData["MensagemSucesso"] = "Carro editado com sucesso";
                    var list= _caminhaoService.ListarOsCaminhoes();
                    return RedirectToAction("Index",list);
                }

                    return View(caminhao);
            }
            catch (System.Exception erro)
            {

                TempData["MensagemErro"] = $"Ops,não foi possível alterar o carro,detalhe do erro :{erro.Message}";
                return RedirectToAction("Index", _caminhaoService.ListarOsCaminhoes());
            }
            
        }
        public IActionResult Apagar(Caminhao caminhao)
        {
            try
            {
                _caminhaoService.ComprarCaminhao(caminhao);
                TempData["MensagemSucesso"] = "Carro apagado com sucesso" ;
                return RedirectToAction("Index");
            }
            catch (System.Exception erro)
            {
                TempData["MensagemErro"] = $"Carro não foi apagado com sucesso{erro.Message}";           
                throw;
            }
            
        }

    }
}

AppFinalCaminhao/Views/Home/Index.cshtml
<div class="text-center">
    <h1 class="display-4">Página Inicial</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>
<div class="d-grid gap-2 d-md-flex justify-content-md-start" >
    <a class="btn btn-dark btn-block" asp-controller="NewViews" asp-action="Create" role="button" >Adicionar Novo Caminhão</a>
</div>
@*<div>
    <table>
    <thead>
        <tr>
            
            <th scope="col" >Nome</th>
            <th scope="col" >Descrição</th>
            <th scope="col" >Data de Criação</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
            {
        <tr>
            <td>@item.Nome</td>
            <td>@item.Descricao</td>
            <td>@item.DataCriacao</td>

        </tr>
            }
    </tbody>
    </table>
</div>
*@
<div>
    Um usuário nos informou que necessita realizar um CRUD de caminhões. Após levantamento, temos a seguinte especificação técnica:

Precisaremos criar uma aplicação Web em C# do tipo ASP.NET Core Web App (Model-View-Controller) na versão 3.1 e sem autenticação;

A entidade Caminhão terá os seguintes atributos:
- Identificação: número inteiro;
- Nome: string;
- Descrição: string;
- Data de Criação: Data e hora;

A tela inicial da aplicação deverá listar todos os caminhões cadastrados;
Os campos para serem apresentados na listagem de caminhões são:

Nome
Descrição
Data de Criação


Para cada caminhão da lista deve haver 3 botões:


Editar -> Deve direcionar o usuário para uma tela para editar os campos do caminhão selecionado;

Detalhes -> Deve direcionar o usuário para uma tela para uma tela para apresentar os detalhes do caminhão selecionado;

Excluir -> Deve direcionar o usuário para uma tela para uma tela com confirmação para que o usuário possa definir se realmente quer deletar o caminhão selecionado;


Ainda na tela inicial deve haver um botão para cadastrar um novo caminhão;
No menu principal da aplicação é necessário um item chamado Caminhões, onde direciona o usuário para a tela de listagem;
</div>

AppFinalCaminhao/Views/NewViews/Create.cshtml
@{
    ViewData["Title"] = "Adiciona caminhão";
}
@model Caminhao
<div class="text-center">
    <h1 class="display-4">Adicionando Caminhão</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<form asp-controller="NewViews" asp-action="Create" method="post" >
  <div class="form-group">
    <label>Nome</label>
    <input type="text" asp-for="Nome" class="form-control" placeholder="Nome do caminhão">
    @Html.ValidationMessageFor(x => x.Nome)
  </div>
  <div class="form-group">
    <label>Descrição</label>
    <input type="text" asp-for="Descricao" class="form-control"  placeholder="Descreva o caminhão">
    @Html.ValidationMessageFor(x => x.Descricao)
  </div>
  <div class="form-group">
    <label>Data de Criação</label>
    <input type="text" asp-for="DataCriacao" class="form-control"  placeholder="Data de criação">
    @Html.ValidationMessageFor(x => x.DataCriacao)
  </div>
   <div class="form-group">
    <label>Modelo</label>
    <input type="number" asp-for="Modelo" class="form-control"  placeholder="Modelo">
    @Html.ValidationMessageFor(x => x.Modelo )
  </div>
  
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
<div>
            Jetta= 0,
            Tiguan = 1,
            Tcross = 2,
            JettaGli = 3,
            UpTsi = 4,
            Passat = 5,
            Up = 6,
            Saveiro = 7,
            Nivus = 8,
            Audi = 9,
</div>

AppFinalCaminhao/Views/NewViews/Delete.cshtml
@{
    ViewData["Title"] = "Compra caminhao";
}
@model Caminhao
<div class="text-center">
    <h1 class="display-4">Compra de caminhão</h1>
    
</div>
<div>
    <div class="text-center" >
    <h3> Realmente deseja comprar o carro  (@Model.Modelo) (@Model.DataCriacao)  </h3>
</div>
<a role="button" class="btn-block btn-secondary" asp-controller="NewViews" asp-action="Index" >Cancelar compra</a>
<a role="button" class="btn-block btn-danger" asp-route-id="@Model.Id" asp-controller="NewViews" asp-action="Apagar">Confirmar compra</a>
</div>

AppFinalCaminhao/Views/NewViews/Details.cshtml
@{
    ViewData["Title"] = "Detalhes do caminhão";
}
@model Caminhao
<div class="text-center">
    <h1 class="display-4">Detalhes do caminhão</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>
<div class="d-grid gap-2 d-md-flex justify-content-md-start" >
    <a class="btn-primary" asp-controller="NewViews" asp-action="Create" role="button" >Adicionar Novo Caminhão</a>
</div>
<div>
    <table class="table">
    <thead>
        <tr>
            <th scope="col">Id#</th>
            <th scope="col" >Nome</th>
            <th scope="col" >Descrição</th>
            <th scope="col" >Data de Criação</th>
            <th scope="col" >Modelo</th>
        </tr>
    </thead>
    <tbody>
                <tr>
            <td>@Model.Id</td>
            <td>@Model.Nome </td>
            <td>@Model.Descricao</td>
            <td>@Model.DataCriacao</td>
            <td>@Model.Modelo</td>
        </tr>
            
        </tbody>
    </table>
</div>

AppFinalCaminhao/Views/NewViews/Edit.cshtml
@{
    ViewData["Title"] = "Edição de Caminhão";
}
@model Caminhao
<div class="text-center">
    <h1 class="display-4">Edição de Caminhão</h1>

</div>
@*é o method post que faz ele ir para a edit httppost na controller?*@
<form asp-controller="NewViews" asp-action="Edit" asp-route-id="@Model.Id" method="post" >
    <input type="hidden " asp-for="Id"  />
  <div class="form-group">
    <label>Nome</label>
    <input asp-for="Nome" asp-controller="NewViews" type="text" class="form-control" placeholder="Nome do caminhão">
    @Html.ValidationMessageFor(x => x.Nome)
  </div>
  <div class="form-group">
    <label>Descrição</label>
    <input type="text" asp-for="Descricao" class="form-control"  placeholder="Descreva o caminhão">
    @Html.ValidationMessageFor(x => x.Descricao)
  </div>
  <div class="form-group">
    <label>Data de Criação</label>
    <input type="text" asp-for="DataCriacao" class="form-control"  placeholder="Data de criação">
    @Html.ValidationMessageFor(x => x.DataCriacao)
  </div>
  <div class="form-group">
    <label>Modelo</label>
    <input type="number" asp-for="Modelo" class="form-control"  placeholder="Modelo">
    @Html.ValidationMessageFor(x => x.Modelo)
  </div>
  <button type="submit" class="btn btn-primary">Atualizar</button>
</form>
<div>
            Jetta= 0,
            Tiguan = 1,
            Tcross = 2,
            JettaGli = 3,
            UpTsi = 4,
            Passat = 5,
            Up = 6,
            Saveiro = 7,
            Nivus = 8,
            Audi = 9,
</div>

AppFinalCaminhao/Views/NewViews/Index.cshtml
@{
    ViewData["Title"] = "Listagem caminhões";
}
@model IEnumerable<Caminhao>

@if(TempData["MensagemSucesso"] != null)
{
<div class="alert alert-success" role="alert">
    <button type="button" class="btn btn-danger btn-sm close-alert " aria-label="Close" >X</button>
  @TempData["MensagemSucesso"]
</div>
}
@if (TempData["MensagemErro"] != null)
{
<div class="alert alert-danger" role="alert">
    <button type="button" class="btn btn-danger btn-sm close-alert " aria-label="Close" >X</button>
  @TempData["MensagemErro"]
</div>
}
<br />

<div class="text-center">
    <h1 class="display-4">Listagem de Caminhões</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>
<div class="d-grid gap-2 d-md-flex justify-content-md-start" >
    <a class="btn btn-dark btn-block" asp-controller="NewViews" asp-action="Create" role="button" >Adicionar Novo Caminhão</a>
</div>
<div>
    <table class="table">
    <thead>
        <tr>
           
            <th scope="col" >Nome</th>
            <th scope="col" >Descrição</th>
            <th scope="col" >Data de Criação</th>
            <th scope="col" >Modelo</th>
        </tr>
    </thead>
    <tbody>
            @foreach(var item in Model)
            {
        <tr>
            <td>@item.Nome</td>
            <td>@item.Descricao</td>
            <td>@item.DataCriacao</td>
            <td>@item.Modelo </td>
            <td>
                <div class="btn-group" role="group" aria-label="Basic example">
                     <a role="button" asp-route-id="@item.Id" asp-controller="NewViews" asp-action="Edit" class="btn btn-primary" >Editar</a>
                    <a role="button" asp-route-id="@item.Id"  asp-controller="NewViews" asp-action="Details" class="btn btn-secondary" >Detalhes</a>
                     <a role="button" asp-route-id="@item.Id" asp-controller="NewViews" asp-action="Delete" class="btn btn-danger" >Comprar</a>
                </div>
            </td>
        </tr>
            }

    </tbody>
    </table>
</div>

AppFinalCaminhao/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppFinalCaminhao</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AppFinalCaminhao</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NewViews" asp-action="Index">Alterar Lista</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - AppFinalCaminhao - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>